services:
  bairros_brasileiros_banco_de_dados:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'bairros_brasileiros'
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "969:3306"
    container_name: bairros_brasileiros_banco_de_dados
  bairros_brasileiros_python:
    build:
      context: .
      dockerfile: ReceitaPython
    volumes:
      - ./app:/app
      - ./migrations:/app/migrations
    ports:
      - "5000:5000"
    container_name: bairros_brasileiros_aplicacao
    working_dir: /app
    environment:
      BAIRROS_BRASILEIROS_DB_HOST: 'bairros_brasileiros_banco_de_dados'
      BAIRROS_BRASILEIROS_DB_NOME: 'bairros_brasileiros'
      BAIRROS_BRASILEIROS_DB_USUARIO: 'root'
      BAIRROS_BRASILEIROS_DB_SENHA: 'bairros_brasileiros'
  bairros_brasileiros_cli:
    build:
      context: .
      dockerfile: CliDockerfile
    volumes:
      - ./cli:/cli
    working_dir: /cli
    environment:
      BAIRROS_BRASILEIROS_DB_HOST: 'bairros_brasileiros_banco_de_dados'
      BAIRROS_BRASILEIROS_DB_NOME: 'bairros_brasileiros'
      BAIRROS_BRASILEIROS_DB_NOME_TESTE: 'bairros_brasileiros_testes'
      BAIRROS_BRASILEIROS_DB_USUARIO: 'root'
      BAIRROS_BRASILEIROS_DB_SENHA: 'bairros_brasileiros'
volumes:
  my-datavolume:

