#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Symfony\Component\Console\Application;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\MigrarCommand;
use Symfony\Component\Console\Command\ListCommand;
use Symfony\Component\Console\Command\HelpCommand;
use Symfony\Component\Translation\Loader\YamlFileLoader;
use Symfony\Component\Translation\Translator;

$translator = new Translator('pt_BR');
$translator->addLoader('yaml', new YamlFileLoader());
$translator->addResource('yaml', __DIR__.'/translations/commands.pt_BR.yml', 'pt_BR');

$listCommand = new ListCommand();
$listCommand
    ->setName($translator->trans('Symfony\Component\Console\Command\ListCommand.name'))
    ->setDescription($translator->trans('Symfony\Component\Console\Command\ListCommand.description'))
    ->setHelp($translator->trans('Symfony\Component\Console\Command\ListCommand.help'))
;


$helpCommand = new HelpCommand();
$helpCommand->setName($translator->trans('Symfony\Component\Console\Command\HelpCommand.name'))
    ->setDescription($translator->trans('Symfony\Component\Console\Command\HelpCommand.description'))
    ->setHelp($translator->trans('Symfony\Component\Console\Command\HelpCommand.help'))
;

$application = new Application();
$application->add(new MigrarCommand());
$application->setDefaultCommand('lista');
$application->add($listCommand);
$application->add($helpCommand);

$application->run();