#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Comandos\AdicionarCidade;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Comandos\MigrarCommand;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Comandos\AjudaBanco;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\TradutorDeComandos;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Aplicacao;

$application = new Aplicacao();

$translator = new TradutorDeComandos('pt_BR', $application);

$translator->traduzirList();
$translator->traduzirHelp();
$translator->traduzirCompletion();

$application->add(new MigrarCommand());
$application->add(new AjudaBanco());
$application->add(new AdicionarCidade());

$definitions = $application->getDefinition();

$application->run();
