#!/usr/bin/env php
<?php

require __DIR__.'/vendor/autoload.php';

use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Comandos\{
    AdicionarCidade,
    MigrarCommand,
    AjudaBanco,
    ListarTodosLocais,
    AdicionarReceita,
    RodarReceita
};
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\TradutorDeComandos;
use Danilocgsilva\BairrosBrasileirosLinhaDeComandos\Aplicacao;

$application = new Aplicacao();

$translator = new TradutorDeComandos('pt_BR', $application);

$translator->traduzirList();
$translator->traduzirHelp();
$translator->traduzirCompletion();

$application->add(new MigrarCommand());
$application->add(new AjudaBanco());
$application->add(new AdicionarCidade());
$application->add(new ListarTodosLocais());
$application->add(new AdicionarReceita());
$application->add(new RodarReceita());

$definitions = $application->getDefinition();

$application->run();
